# Generated by Django 5.2.5 on 2025-09-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='endereco_cep',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='endereco_cidade',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='endereco_estado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_city',
            field=models.CharField(default=2, max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_state',
            field=models.CharField(default=4, max_length=50, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_zip',
            field=models.CharField(default=2, max_length=10, verbose_name='ZIP Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
