version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  app:
    image: myapp:latest
    build: ./app
    environment:
      - APP_ENV=production
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=User
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webnet