
services:
  app: 
    container_name: app
    build: .
    command: bash -c "./prestart.sh"
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    depends_on:
        - db

  db:
    image: postgres
    environment:
      - POSTGRES_NAME=User
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: