# Generated by Django 5.2.5 on 2025-09-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(default='00.000.000/0000-00', max_length=18)),
                ('image', models.ImageField(default='default.jpg', upload_to='midias/')),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupom_fiscal.fiscalcoupon')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupom_fiscal.product')),
            ],
        ),
        migrations.AddField(
            model_name='fiscalcoupon',
            name='products',
            field=models.ManyToManyField(related_name='coupons', through='cupom_fiscal.Pivo', to='cupom_fiscal.product'),
        ),
    ]
