# Generated by Django 5.2.5 on 2025-09-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupomfiscal',
            name='imagem',
        ),
    ]
