# Generated by Django 5.2.5 on 2025-09-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0002_remove_cupomfiscal_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupomfiscal',
            name='id',
        ),
        migrations.AddField(
            model_name='cupomfiscal',
            name='id_cupom',
            field=models.CharField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
