# Generated by Django 5.2.5 on 2025-09-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0003_remove_cupomfiscal_id_cupomfiscal_id_cupom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupomfiscal',
            name='id_cupom',
        ),
        migrations.AddField(
            model_name='cupomfiscal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
