# Generated by Django 5.2.5 on 2025-09-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0004_remove_cupomfiscal_id_cupom_cupomfiscal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupomfiscal',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=18),
        ),
        migrations.AddField(
            model_name='cupomfiscal',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='midias/'),
        ),
    ]
