# Generated by Django 5.2.5 on 2025-09-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0005_cupomfiscal_cnpj_cupomfiscal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupomfiscal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
