# Generated by Django 5.2.5 on 2025-09-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0007_itemproduct_remove_cupomfiscal_usuario_fiscalcoupon'),
        ('num_sorte', '0003_remove_numerosorte_cupom_fiscal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CupomFiscal',
        ),
    ]
