# Generated by Django 5.2.5 on 2025-09-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0008_delete_cupomfiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemProduct',
        ),
        migrations.RemoveField(
            model_name='fiscalcoupon',
            name='product_name',
        ),
        migrations.AddField(
            model_name='pivo',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupom_fiscal.fiscalcoupon'),
        ),
        migrations.AddField(
            model_name='pivo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupom_fiscal.product'),
        ),
        migrations.AddField(
            model_name='fiscalcoupon',
            name='products',
            field=models.ManyToManyField(related_name='coupons', through='cupom_fiscal.Pivo', to='cupom_fiscal.product'),
        ),
    ]
