# Generated by Django 5.2.5 on 2025-09-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0009_pivo_product_delete_itemproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pivo',
            old_name='product',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='fiscalcoupon',
            name='quantity',
        ),
        migrations.AddField(
            model_name='pivo',
            name='quantity',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
