# Generated by Django 5.2.5 on 2025-09-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0010_rename_product_pivo_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pivo',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fiscalcoupon',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
