# Generated by Django 5.2.5 on 2025-09-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_fiscal', '0011_remove_pivo_quantity_fiscalcoupon_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalcoupon',
            name='quantity',
        ),
        migrations.AddField(
            model_name='pivo',
            name='quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
