# Generated by Django 5.2.5 on 2025-09-03 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupom_fiscal', '0003_remove_cupomfiscal_id_cupomfiscal_id_cupom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleNumeroSorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número da Sorte')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lote', models.IntegerField(max_length=50, verbose_name='Lote')),
                ('serie', models.IntegerField(max_length=50, verbose_name='Série')),
                ('max_serie', models.IntegerField(max_length=99999, verbose_name='Máxima Série')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroSorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número da Sorte')),
                ('cupom_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_sorte', to='cupom_fiscal.cupomfiscal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_sorte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
