# Generated by Django 5.2.5 on 2025-09-12 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupom_fiscal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Lucky Number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_numbers', to='cupom_fiscal.fiscalcoupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LuckyNumberControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(verbose_name='Batch')),
                ('series', models.IntegerField(verbose_name='Series')),
                ('max_series', models.IntegerField(verbose_name='Max Series')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_controls', to='num_sorte.luckynumber')),
            ],
        ),
    ]
