# Generated by Django 5.2.5 on 2025-09-03 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num_sorte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlenumerosorte',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='numerosorte',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='controlenumerosorte',
            name='lote',
            field=models.IntegerField(verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='controlenumerosorte',
            name='max_serie',
            field=models.IntegerField(verbose_name='Máxima Série'),
        ),
        migrations.AlterField(
            model_name='controlenumerosorte',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_numeros', to='num_sorte.numerosorte'),
        ),
        migrations.AlterField(
            model_name='controlenumerosorte',
            name='serie',
            field=models.IntegerField(verbose_name='Série'),
        ),
    ]
