# Generated by Django 5.2.5 on 2025-09-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceps',
            fields=[
                ('cep', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('uf', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('state', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adresses.states')),
            ],
        ),
    ]
