# Generated by Django 5.2.5 on 2025-09-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0002_load_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceps',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='citydefault', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ceps',
            name='state',
            field=models.CharField(blank=True, db_index=True, default='statesdefault', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ceps',
            name='street',
            field=models.CharField(blank=True, db_index=True, default='streetdefault', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(blank=True, default='cityname', max_length=300),
        ),
        migrations.AlterField(
            model_name='states',
            name='name',
            field=models.CharField(blank=True, default='cityname', max_length=300),
        ),
        migrations.AlterField(
            model_name='states',
            name='uf',
            field=models.CharField(blank=True, default='uf', max_length=50),
        ),
    ]
