# Generated by Django 5.2.5 on 2025-09-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoliticaPrivacidade',
            new_name='PrivacyPolicy',
        ),
        migrations.RenameModel(
            old_name='Regulamento',
            new_name='Regulations',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='resposta',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='pergunta',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='privacypolicy',
            old_name='conteudo',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='regulations',
            old_name='conteudo',
            new_name='content',
        ),
    ]
