# Generated by Django 5.2.5 on 2025-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_politicaprivacidade_privacypolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='file',
            field=models.ImageField(default=2, upload_to='PrivacyPolicy/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulations',
            name='file',
            field=models.ImageField(default=98, upload_to='Regulations/'),
            preserve_default=False,
        ),
    ]
